
# Docker Compose Version
version: "3.7"

# Containers
services:

  # Frontend
  app:
    # Refered Dockerfile
    build: ./
    container_name: MyWorkspace-App_NodeJS
    command: npm run dev
    user: root
    networks:
      - default
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/MyWorkspace/
    depends_on:
     - db
    links:
     - db

  # Backend
  db:
    image: postgres:latest
    container_name: MyWorkspace-DB_PostgreSQL
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: myworkspace_db
    user: root
    networks:
      - default
    #command: sudo -u postgres createuser db_user; sudo -u postgres createdb myworkspace_db; sudo -u postgres psql;
    # psql=# alter user db_user with encrypted password 'pass';
    # psql=# grant all privileges on database myworkspace_db to db_user;
    volumes:
      - ./.docker/docker_containers/postgresql/:/var/lib/postgresql/
    ports:
      - 5432:5432

# Networks for Containers
networks:
  default:
    driver: bridge
